- name: Copy systemd service file
  copy:
    src: "{{ app.service.name }}.service"
    dest: /etc/systemd/system/
  become: yes

- name: Enable systemd service
  systemd:
    name: "{{ app.service.name }}"
    enabled: yes
    masked: no
  become: yes
