- name: Copy torrent script
  template:
    src: gomovies_torrent_add.sh.j2
    dest: "{{ ansible_env.HOME }}/bin/gomovies_torrent_add.sh"
- name: Make script executable
  file:
    path: "{{ ansible_env.HOME }}/bin/gomovies_torrent_add.sh"
    mode: u+x
