- name: Create web UI targer directory
  file:
    path: "{{ app.config.web_dir }}"
    state: directory

- name: Copy web UI tar archive to raspberry PI
  unarchive:
    src: "{{ web_ui_tar }}"
    dest: "{{ app.config.web_dir }}/"
    extra_opts:
      - --strip-components=1
